In [ ]:
%pip install numpy

In [2]:
import numpy as np

In [5]:
a = np.array([1, 2, 3]) #массив
a

array([1, 2, 3])

In [6]:
a[1] = 'string' #нельзя менять тип данных

ValueError: invalid literal for int() with base 10: 'string'

In [7]:
a[0]

1

In [8]:
a[1:]

array([2, 3])

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])

b = a[3:]

b[0] = 10

a

array([ 1,  2,  3, 10,  5,  6])

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a[0][1]

2

In [15]:
a[0, 1:]

array([2, 3])

In [16]:
a[:, 1:]

array([[2, 3],
       [5, 6]])

In [17]:
a.ndim #размерность

2

In [19]:
a.shape #размер

(2, 3)

In [21]:
a.size #количество элементов

6

In [23]:
a.dtype #тип данных

dtype('int64')

# Создание массивов

In [27]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.ones((4, 3, 2), dtype=np.int16)

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int16)

In [41]:
np.empty((2, 3))

array([[6.38145038e-310, 2.88254894e-316, 2.37663529e-312],
       [2.56761491e-312, 8.48798317e-313, 9.33678148e-313]])

In [42]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [45]:
np.linspace(0, 10, 5) #5 чисел от 0 до 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [48]:
np.linspace(0, 10, 20) #20 чисел от 0 до 10

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# sort and concatenate

In [49]:
a = np.array([2, 1, 4, 5, 3, 7, 6, 8, 9, 10])

In [50]:
np.sort(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
np.argsort(a)

array([1, 0, 4, 2, 3, 6, 5, 7, 8, 9])

In [52]:
np.searchsorted(a, 6) #поиск 6 в отсортированном списке

5

In [57]:
np.partition(a, (3, 1))

array([ 1,  2,  3,  4,  5,  7,  6,  8,  9, 10])

In [64]:
a = np.array([[2, 1, 4, 9, 3], [7, 6, 8, 5, 10]])
a

array([[ 2,  1,  4,  9,  3],
       [ 7,  6,  8,  5, 10]])

In [65]:
np.sort(a, axis=1)

array([[ 1,  2,  3,  4,  9],
       [ 5,  6,  7,  8, 10]])

In [66]:
np.sort(a, axis=0)

array([[ 2,  1,  4,  5,  3],
       [ 7,  6,  8,  9, 10]])

In [74]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2])

In [75]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 1, 2])

In [77]:
np.concatenate((a, b), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [71]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [72]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

# изменение формы

In [83]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
a.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [86]:
a.reshape(2, 3, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [88]:
a.reshape(2, -1, 2) # -1 - любое число

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [89]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [90]:
a[np.newaxis, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [91]:
a[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [92]:
np.expand_dims(a, axis=0)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [93]:
np.expand_dims(a, axis=1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

# Индексация и фильтрация

In [105]:
a = np.random.randint(0, 10, 10)
a

array([4, 3, 2, 2, 3, 1, 4, 2, 9, 3])

In [99]:
a[:5]

array([0, 8, 2, 3, 8])

In [100]:
a[a < 5]

array([0, 2, 3, 2])

In [101]:
a < 5

array([ True, False,  True,  True, False, False, False,  True, False,
       False])

In [102]:
a[a%2==0]

array([0, 8, 2, 8, 6, 2, 6, 6])

In [108]:
a[(a%2==0) & (a < 5)]

array([4, 2, 2, 4, 2])

# Математические операции

In [109]:
a = np.random.randint(0, 10, 10)
a

array([4, 5, 1, 2, 9, 4, 8, 2, 3, 9])

In [110]:
b = np.random.randint(0, 10, 10)
b

array([4, 3, 7, 4, 4, 6, 6, 5, 7, 2])

In [112]:
a + 5.4

array([ 9.4, 10.4,  6.4,  7.4, 14.4,  9.4, 13.4,  7.4,  8.4, 14.4])

In [113]:
a * 5.4

array([21.6, 27. ,  5.4, 10.8, 48.6, 21.6, 43.2, 10.8, 16.2, 48.6])

In [114]:
a + b

array([ 8,  8,  8,  6, 13, 10, 14,  7, 10, 11])

In [115]:
a * b

array([16, 15,  7,  8, 36, 24, 48, 10, 21, 18])

In [118]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[2, 2, 2], [2, 2, 2]])
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[2, 2, 2],
        [2, 2, 2]]))

In [121]:
a.T @ b

array([[10, 10, 10],
       [14, 14, 14],
       [18, 18, 18]])

In [122]:
a.min()

1

In [123]:
a.max()

6

In [124]:
a.sum()

21

In [125]:
a.mean()

3.5

In [126]:
a.std()

1.707825127659933

In [8]:
y = 2024
m = 3


f"{y}-{m:010}"

'2024-0000000003'

In [10]:
"%d-%0d" % (y, m)

'2024-3'